# Generated by Django 4.1.4 on 2023-01-03 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.FloatField(null=True, verbose_name='Цена'),
        ),
    ]
