# Generated by Django 4.1.4 on 2023-01-29 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0002_alter_order_user_comment_alter_order_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('Оплата картой', 'Оплата картой'), ('Оплата наличными', 'Оплата наличными'), ('Оплата переводом через банк', 'Оплата переводом через банк')], max_length=50, verbose_name='Способ оплаты'),
        ),
    ]
