# Generated by Django 4.1.4 on 2023-01-17 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0003_alter_cart_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='published_at',
            field=models.DateTimeField(verbose_name='Заказ создан'),
        ),
    ]
