# Generated by Django 4.1.4 on 2023-01-29 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0003_alter_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='user_phone',
            field=models.CharField(max_length=50, verbose_name='Номер телефона'),
        ),
    ]
