# Generated by Django 4.1.4 on 2023-02-07 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0004_alter_category_options_rename_name_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('В процессе', 'В процессе'), ('Выполнен', 'Выполнен'), ('Отменен', 'Отменен')], max_length=50, verbose_name='Статус заказа'),
        ),
    ]
