# Generated by Django 4.1.4 on 2023-02-10 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0005_alter_order_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название логотипа')),
                ('image_category', models.ImageField(upload_to='')),
            ],
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['order_creation_time'], 'verbose_name': 'Заказ клиента', 'verbose_name_plural': 'Заказы клиентов (Работает администратор!!!)'},
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Принят', 'Принят'), ('В процессе', 'В процессе'), ('Выполнен', 'Выполнен'), ('Отменен', 'Отменен')], default='Принят', max_length=50, verbose_name='Статус заказа'),
        ),
    ]
