# Generated by Django 4.1.4 on 2023-01-17 13:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('delivery_app', '0005_alter_cart_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='dish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='delivery_app.dish', verbose_name='Блюдо'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 17, 13, 37, 3, 380868, tzinfo=datetime.timezone.utc), verbose_name='Заказ создан'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
