# Generated by Django 4.1.4 on 2023-01-21 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0006_alter_cart_dish_alter_cart_published_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='published_at',
            field=models.DateTimeField(verbose_name='Заказ создан'),
        ),
    ]
