# Generated by Django 4.1.4 on 2023-02-10 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0006_logo_alter_order_options_alter_order_order_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='logo',
            options={'ordering': ['name'], 'verbose_name': 'Логотип', 'verbose_name_plural': 'Логотипы'},
        ),
    ]
