# Generated by Django 4.1.4 on 2023-01-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_app', '0007_alter_cart_published_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='count_of_dishes',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество блюд'),
        ),
    ]
